# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/h2amer/work/workspace/bbp_jpeg/jpeg_tcm_no_cv/jpeg_tcm_cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/h2amer/work/workspace/bbp_jpeg/jpeg_tcm_no_cv/jpeg_tcm_cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/h2amer/work/workspace/bbp_jpeg/jpeg_tcm_no_cv/jpeg_tcm_cmake/CMakeFiles /home/h2amer/work/workspace/bbp_jpeg/jpeg_tcm_no_cv/jpeg_tcm_cmake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/h2amer/work/workspace/bbp_jpeg/jpeg_tcm_no_cv/jpeg_tcm_cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/component.o: src/component.cpp.o

.PHONY : src/component.o

# target to build an object file
src/component.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/component.cpp.o
.PHONY : src/component.cpp.o

src/component.i: src/component.cpp.i

.PHONY : src/component.i

# target to preprocess a source file
src/component.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/component.cpp.i
.PHONY : src/component.cpp.i

src/component.s: src/component.cpp.s

.PHONY : src/component.s

# target to generate assembly for a file
src/component.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/component.cpp.s
.PHONY : src/component.cpp.s

src/exportpicture.o: src/exportpicture.cpp.o

.PHONY : src/exportpicture.o

# target to build an object file
src/exportpicture.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exportpicture.cpp.o
.PHONY : src/exportpicture.cpp.o

src/exportpicture.i: src/exportpicture.cpp.i

.PHONY : src/exportpicture.i

# target to preprocess a source file
src/exportpicture.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exportpicture.cpp.i
.PHONY : src/exportpicture.cpp.i

src/exportpicture.s: src/exportpicture.cpp.s

.PHONY : src/exportpicture.s

# target to generate assembly for a file
src/exportpicture.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exportpicture.cpp.s
.PHONY : src/exportpicture.cpp.s

src/huffmanelementscount.o: src/huffmanelementscount.cpp.o

.PHONY : src/huffmanelementscount.o

# target to build an object file
src/huffmanelementscount.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/huffmanelementscount.cpp.o
.PHONY : src/huffmanelementscount.cpp.o

src/huffmanelementscount.i: src/huffmanelementscount.cpp.i

.PHONY : src/huffmanelementscount.i

# target to preprocess a source file
src/huffmanelementscount.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/huffmanelementscount.cpp.i
.PHONY : src/huffmanelementscount.cpp.i

src/huffmanelementscount.s: src/huffmanelementscount.cpp.s

.PHONY : src/huffmanelementscount.s

# target to generate assembly for a file
src/huffmanelementscount.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/huffmanelementscount.cpp.s
.PHONY : src/huffmanelementscount.cpp.s

src/huffmantable.o: src/huffmantable.cpp.o

.PHONY : src/huffmantable.o

# target to build an object file
src/huffmantable.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/huffmantable.cpp.o
.PHONY : src/huffmantable.cpp.o

src/huffmantable.i: src/huffmantable.cpp.i

.PHONY : src/huffmantable.i

# target to preprocess a source file
src/huffmantable.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/huffmantable.cpp.i
.PHONY : src/huffmantable.cpp.i

src/huffmantable.s: src/huffmantable.cpp.s

.PHONY : src/huffmantable.s

# target to generate assembly for a file
src/huffmantable.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/huffmantable.cpp.s
.PHONY : src/huffmantable.cpp.s

src/jpegdecoder.o: src/jpegdecoder.cpp.o

.PHONY : src/jpegdecoder.o

# target to build an object file
src/jpegdecoder.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jpegdecoder.cpp.o
.PHONY : src/jpegdecoder.cpp.o

src/jpegdecoder.i: src/jpegdecoder.cpp.i

.PHONY : src/jpegdecoder.i

# target to preprocess a source file
src/jpegdecoder.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jpegdecoder.cpp.i
.PHONY : src/jpegdecoder.cpp.i

src/jpegdecoder.s: src/jpegdecoder.cpp.s

.PHONY : src/jpegdecoder.s

# target to generate assembly for a file
src/jpegdecoder.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jpegdecoder.cpp.s
.PHONY : src/jpegdecoder.cpp.s

src/jpegencoder.o: src/jpegencoder.cpp.o

.PHONY : src/jpegencoder.o

# target to build an object file
src/jpegencoder.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jpegencoder.cpp.o
.PHONY : src/jpegencoder.cpp.o

src/jpegencoder.i: src/jpegencoder.cpp.i

.PHONY : src/jpegencoder.i

# target to preprocess a source file
src/jpegencoder.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jpegencoder.cpp.i
.PHONY : src/jpegencoder.cpp.i

src/jpegencoder.s: src/jpegencoder.cpp.s

.PHONY : src/jpegencoder.s

# target to generate assembly for a file
src/jpegencoder.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jpegencoder.cpp.s
.PHONY : src/jpegencoder.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/quantizationtable.o: src/quantizationtable.cpp.o

.PHONY : src/quantizationtable.o

# target to build an object file
src/quantizationtable.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/quantizationtable.cpp.o
.PHONY : src/quantizationtable.cpp.o

src/quantizationtable.i: src/quantizationtable.cpp.i

.PHONY : src/quantizationtable.i

# target to preprocess a source file
src/quantizationtable.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/quantizationtable.cpp.i
.PHONY : src/quantizationtable.cpp.i

src/quantizationtable.s: src/quantizationtable.cpp.s

.PHONY : src/quantizationtable.s

# target to generate assembly for a file
src/quantizationtable.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/quantizationtable.cpp.s
.PHONY : src/quantizationtable.cpp.s

src/tcm_1.o: src/tcm_1.cpp.o

.PHONY : src/tcm_1.o

# target to build an object file
src/tcm_1.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tcm_1.cpp.o
.PHONY : src/tcm_1.cpp.o

src/tcm_1.i: src/tcm_1.cpp.i

.PHONY : src/tcm_1.i

# target to preprocess a source file
src/tcm_1.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tcm_1.cpp.i
.PHONY : src/tcm_1.cpp.i

src/tcm_1.s: src/tcm_1.cpp.s

.PHONY : src/tcm_1.s

# target to generate assembly for a file
src/tcm_1.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tcm_1.cpp.s
.PHONY : src/tcm_1.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... src/component.o"
	@echo "... src/component.i"
	@echo "... src/component.s"
	@echo "... src/exportpicture.o"
	@echo "... src/exportpicture.i"
	@echo "... src/exportpicture.s"
	@echo "... src/huffmanelementscount.o"
	@echo "... src/huffmanelementscount.i"
	@echo "... src/huffmanelementscount.s"
	@echo "... src/huffmantable.o"
	@echo "... src/huffmantable.i"
	@echo "... src/huffmantable.s"
	@echo "... src/jpegdecoder.o"
	@echo "... src/jpegdecoder.i"
	@echo "... src/jpegdecoder.s"
	@echo "... src/jpegencoder.o"
	@echo "... src/jpegencoder.i"
	@echo "... src/jpegencoder.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/quantizationtable.o"
	@echo "... src/quantizationtable.i"
	@echo "... src/quantizationtable.s"
	@echo "... src/tcm_1.o"
	@echo "... src/tcm_1.i"
	@echo "... src/tcm_1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

